# Generated by rzig::document(). Do not edit.

#' Compute one single-term Li-Pearl probability-of-causation interval.
#' @param kind Theorem number, 4 through 7.
#' @param aji Interventional probability for the target treatment and outcome.
#' @param oji Observed joint probability for the target treatment and outcome.
#' @param vi Observed marginal probability of the target outcome.
#' @param vk Observed marginal probability of the factual outcome.
#' @param uj Observed probability of the target treatment.
#' @param up Observed probability of the factual treatment.
#' @param opk Observed joint probability of factual treatment and outcome.
#' @param ojk Observed joint probability of target treatment and factual outcome.
#' @param other_ok Observed factual-outcome probabilities for other treatments.
#' @return Lower and upper bounds.
#'
#' @export
poc_single_zig <- function(kind, aji, oji, vi, vk, uj, up, opk, ojk, other_ok) {
  .Call(poc_single_zig_, kind, aji, oji, vi, vk, uj, up, opk, ojk, other_ok)
}

#' Evaluate the complete printed Li-Pearl analytical recursion in Zig.
#' @param m Number of treatment levels, at least two.
#' @param n Number of outcome levels, at least two.
#' @param observed Joint probabilities in column-major matrix order.
#' @param intervention Intervention probabilities in column-major order.
#' @param x Distinct one-based counterfactual treatment indices.
#' @param y Corresponding one-based outcome indices.
#' @param observed_x One-based factual treatment index, or zero for none.
#' @param observed_y One-based factual outcome index, or zero for none.
#' @param tolerance Positive probability-consistency tolerance.
#' @return Unconditional lower and upper bounds. The memo is limited to 1048576 states.
#'
#' @export
poc_paper_zig <- function(m, n, observed, intervention, x, y, observed_x, observed_y, tolerance) {
  .Call(poc_paper_zig_, m, n, observed, intervention, x, y, observed_x, observed_y, tolerance)
}

#' Evaluate the Shu-Wang-Li closed form and the labelled repeated-outcome extension.
#' @param m Number of treatment levels, at least two.
#' @param n Number of outcome levels, at least two.
#' @param observed Joint probabilities in column-major matrix order.
#' @param intervention Intervention probabilities in column-major order.
#' @param x Distinct one-based counterfactual treatment indices.
#' @param y Corresponding one-based outcome indices.
#' @param observed_x One-based factual treatment index, or zero for none.
#' @param observed_y One-based factual outcome index, or zero for none.
#' @param tolerance Positive probability-consistency tolerance.
#' @return Lower and upper bounds, family code and consistency-reduction flag.
#' Family codes 0-6 denote factual margin, contradiction, theorems 2-5, and the
#' repeated-outcome extension. The complete input table has at most 1048576 cells.
#'
#' @export
poc_shu_zig <- function(m, n, observed, intervention, x, y, observed_x, observed_y, tolerance) {
  .Call(poc_shu_zig_, m, n, observed, intervention, x, y, observed_x, observed_y, tolerance)
}

#' Solve a continuous nonnegative-variable LP using the native two-phase solver.
#' @param m Number of constraint rows, possibly zero.
#' @param n Number of variables, at least one.
#' @param a Constraint matrix in column-major order.
#' @param b Constraint right-hand sides.
#' @param directions Integer directions: -1 for less-than, 0 equality, 1 greater-than.
#' @param objective Objective coefficients.
#' @param maximize Logical maximization flag.
#' @param max_iterations Positive pivot limit, normally 200000.
#' @return Numeric vector: status (0 optimal, 2 infeasible, 3 unbounded), objective,
#' iterations, primal violation, dual violation, duality gap, then n primal values,
#' m dual values and n ray values. Infeasible dual values are a Farkas certificate;
#' an unbounded result contains a feasible point and improving ray. Nonoptimal
#' objective values are NaN. Numerical failures and resource limits raise errors.
#' Pivot and certificate tolerances are 1e-10 and 1e-8; tableau plus lexicographic
#' scratch is capped at 16777216 cells. Pivoting uses an improving coefficient
#' and symbolic lexicographic row ordering without changing constraint values.
#'
#' @export
poc_lp_zig <- function(m, n, a, b, directions, objective, maximize, max_iterations) {
  .Call(poc_lp_zig_, m, n, a, b, directions, objective, maximize, max_iterations)
}

#' Construct the complete static response-type system in native code.
#' @param m Number of treatment levels, at least two.
#' @param n Number of outcome levels, at least two.
#' @param observed Observational margins in column-major order, copied unchanged.
#' @param intervention Interventional margins in column-major order, copied unchanged.
#' @param max_variables Positive response-variable cap.
#' @return Numeric vector: variable count V, row count K, response-type count,
#' then V*m response codes, V factual-X codes, V factual-Y codes, K*V constraint
#' coefficients and K right-hand sides. Matrices are column-major. Output is
#' capped at 16777216 doubles. R retains probability/label validation.
#'
#' @export
poc_static_system_zig <- function(m, n, observed, intervention, max_variables) {
  .Call(poc_static_system_zig_, m, n, observed, intervention, max_variables)
}

#' Evaluate a categorical response-type conjunction and factual condition.
#' @param variables Number of response-distribution cells.
#' @param m Number of treatment columns, at least two.
#' @param response Positive integer potential-outcome codes, column-major.
#' @param factual_x One-based factual treatment indices.
#' @param factual_y Factual outcome codes consistent with the response matrix.
#' @param x Distinct one-based counterfactual treatment indices; may be empty.
#' @param y Corresponding positive outcome codes.
#' @param observed_x One-based factual treatment or zero for no condition.
#' @param observed_y Positive factual outcome code or zero for no condition.
#' @return Numeric zero/one event mask. At most 16777216 response cells.
#'
#' @export
poc_static_event_zig <- function(variables, m, response, factual_x, factual_y, x, y, observed_x, observed_y) {
  .Call(poc_static_event_zig_, variables, m, response, factual_x, factual_y, x, y, observed_x, observed_y)
}
